"""empty message

Revision ID: 2d197ca3c111
Revises: 4d121aaedd97
Create Date: 2020-12-23 21:23:44.679000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d197ca3c111'
down_revision = '4d121aaedd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.drop_constraint(u'Show_venue_id_fkey', 'Show', type_='foreignkey')
    op.drop_constraint(u'Show_artist_id_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'artist_id')
    op.drop_column('Show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'Show_artist_id_fkey', 'Show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(u'Show_venue_id_fkey', 'Show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('Show', 'image_link')
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
