"""empty message

Revision ID: a26be21c6d5f
Revises: 2d197ca3c111
Create Date: 2020-12-23 22:01:53.526000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26be21c6d5f'
down_revision = '2d197ca3c111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venu', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seek_venur')
    op.drop_column('Artist', 'seek_description')
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    op.add_column('Artist', sa.Column('seek_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('seek_venur', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venu')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
