"""empty message

Revision ID: cc62d9798a90
Revises: 3089d9b0d020
Create Date: 2020-12-23 19:55:27.802000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc62d9798a90'
down_revision = '3089d9b0d020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('City',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ArtistGenres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_rime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id')
    )
    op.add_column(u'Artist', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column(u'Artist', sa.Column('seek_description', sa.String(), nullable=True))
    op.add_column(u'Artist', sa.Column('seek_venur', sa.Boolean(), nullable=True))
    op.add_column(u'Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'Artist', 'City', ['city_id'], ['id'])
    op.drop_column(u'Artist', 'city')
    op.drop_column(u'Artist', 'genres')
    op.drop_column(u'Artist', 'state')
    op.add_column(u'Venue', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'City', ['city_id'], ['id'])
    op.drop_column(u'Venue', 'city')
    op.drop_column(u'Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column(u'Venue', 'city_id')
    op.add_column(u'Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column(u'Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column(u'Artist', 'website_link')
    op.drop_column(u'Artist', 'seek_venur')
    op.drop_column(u'Artist', 'seek_description')
    op.drop_column(u'Artist', 'city_id')
    op.drop_table('Show')
    op.drop_table('ArtistGenres')
    op.drop_table('City')
    # ### end Alembic commands ###
